Add version selector (#28)
* Add mike for version handling

* Integrate mike in docs build workflow

* Improve version deployment logic

diff --git a/.github/workflows/build-docs.yaml b/.github/workflows/build-docs.yaml
--- a/.github/workflows/build-docs.yaml
+++ b/.github/workflows/build-docs.yaml
@@ -3,8 +3,10 @@ name: Build and deploy documentation
 on:
   push:
     branches:
-      - main
       - develop
+    tags:
+      - 'v*'
+
   workflow_dispatch:
 
 jobs:
@@ -58,14 +60,52 @@ jobs:
         env:
           BRANCH: ${{ vars.MONOREPO_DEV_BRANCH }}
 
-      - name: Build documentation
+      - name: Set git credentials
         run: |
-          cd src
-          hatch run mkdocs build 
+          git config --global user.name "${{ github.actor }}"
+          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
 
-      - name: Deploy to GitHub Pages
-        uses: peaceiris/actions-gh-pages@v4
-        with:
-          personal_token: ${{ secrets.GITHUB_TOKEN }}
-          publish_dir: ./src/site
-          cname: dev.getml.com
+      - name: Deploy dev version if develop branch
+        if: "github.ref == 'refs/heads/develop'"
+        run: |
+          hatch run mike deploy --config-file ./src/mkdocs.yml dev
+
+      - name: Deploy release version if tag
+        if: "startsWith(github.ref, 'refs/tags/v')"
+        run: |
+          TAG_VERSION=$(echo "${{ github.ref }}" | sed -n 's/refs\/tags\/v\([0-9]\+\.[0-9]\+\).*/\1/p')
+
+          if [[ -z "$TAG_VERSION" ]]; then
+            echo "TAG_VERSION could not be obtained from ${{ github.ref }}. Make sure the tag has 'vX.Y' in the beginning (e.g v1.5). Exiting.."
+            exit 1
+          fi
+
+          LATEST_DEPLOYED_VERSION=$(hatch run mike list --config-file ./src/mkdocs.yml | grep -E '^[0-9]+\.[0-9]+' | awk '{print $1}' | sort -V | tail -n 1)
+
+          if [[ -z $LATEST_DEPLOYED_VERSION ]]; then
+            echo "No numbered deployed version found. Deploying $TAG_VERSION with the latest alias"
+            hatch run mike deploy --config-file ./src/mkdocs.yml $TAG_VERSION latest
+
+          elif [[ $(echo -e "$TAG_VERSION\n$LATEST_DEPLOYED_VERSION" | sort -V | tail -n 1) == "$TAG_VERSION" && "$TAG_VERSION" != "$LATEST_DEPLOYED_VERSION"]]; then
+            echo "Tag version ($TAG_VERSION) is higher than the currently deployed latest version ($LATEST_DEPLOYED_VERSION). Deploying $TAG_VERSION with the latest alias"
+            hatch run mike deploy --config-file ./src/mkdocs.yml --update-aliases $TAG_VERSION latest
+
+          else
+            echo "Tag version ($TAG_VERSION) is not higher than the currently deployed latest version ($LATEST_DEPLOYED_VERSION). Deploying $TAG_VERSION without updating the latest alias"
+            hatch run mike deploy --config-file ./src/mkdocs.yml $TAG_VERSION
+            
+          fi
+
+      - name: Add CNAME file
+        run: |
+          git checkout gh-pages
+          if [ ! -f CNAME ]; then
+          echo "dev.getml.com" > CNAME
+
+          git add CNAME
+          git commit -m "Add CNAME file if it doesn't exist"
+          fi
+      
+      - name: Push all changes to gh-pages
+        run: |
+          git push origin gh-pages
